### ISSUE TITLE
[NOBUG] I want to share my fork!

### ISSUE THREAD

**Issue by amreo** [manio/hard#1]
Hi!
I simply want to share you my fork: https://github.com/amreo/hard-sun2000-influxdb-datalogger
It is designed my use case and not for a PR, so I have done some customizations

**Comment by manio** [comment]
Nice, thank you for sharing this :)
In fact my project is also designed for my use case and I am not going to merge PRs (at least something I may find valuable to have).
I hope it was a good base for your changes :)
